version: "3.8"

services:
  server:
    build: ./src/server
    ports:
      - "127.0.0.1:${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - ./src/server:/server
      - .:/workspaces/OmicsCopilot:cached
    env_file:
      - .env
    command: ./run_server.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  client:
    build: ./src/client
    ports:
      - "127.0.0.1:${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}"
    volumes:
      - ./src/client:/client
    env_file:
      - .env
    command: ./run_client.sh
