name: OmicsCopilot CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.11.1
